/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionNewRouteImport } from './routes/session/new'
import { Route as SessionSessionIdTransitionRouteImport } from './routes/session/$sessionId/transition'
import { Route as SessionSessionIdSummaryRouteImport } from './routes/session/$sessionId/summary'
import { Route as SessionSessionIdRequestRouteImport } from './routes/session/$sessionId/request'
import { Route as SessionSessionIdReadinessRouteImport } from './routes/session/$sessionId/readiness'
import { Route as SessionSessionIdProblemRouteImport } from './routes/session/$sessionId/problem'
import { Route as SessionSessionIdIStatementRouteImport } from './routes/session/$sessionId/i-statement'
import { Route as SessionSessionIdApproachRouteImport } from './routes/session/$sessionId/approach'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionNewRoute = SessionNewRouteImport.update({
  id: '/session/new',
  path: '/session/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdTransitionRoute =
  SessionSessionIdTransitionRouteImport.update({
    id: '/session/$sessionId/transition',
    path: '/session/$sessionId/transition',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionSessionIdSummaryRoute = SessionSessionIdSummaryRouteImport.update({
  id: '/session/$sessionId/summary',
  path: '/session/$sessionId/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRequestRoute = SessionSessionIdRequestRouteImport.update({
  id: '/session/$sessionId/request',
  path: '/session/$sessionId/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdReadinessRoute =
  SessionSessionIdReadinessRouteImport.update({
    id: '/session/$sessionId/readiness',
    path: '/session/$sessionId/readiness',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionSessionIdProblemRoute = SessionSessionIdProblemRouteImport.update({
  id: '/session/$sessionId/problem',
  path: '/session/$sessionId/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdIStatementRoute =
  SessionSessionIdIStatementRouteImport.update({
    id: '/session/$sessionId/i-statement',
    path: '/session/$sessionId/i-statement',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionSessionIdApproachRoute =
  SessionSessionIdApproachRouteImport.update({
    id: '/session/$sessionId/approach',
    path: '/session/$sessionId/approach',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/session/new': typeof SessionNewRoute
  '/session/$sessionId/approach': typeof SessionSessionIdApproachRoute
  '/session/$sessionId/i-statement': typeof SessionSessionIdIStatementRoute
  '/session/$sessionId/problem': typeof SessionSessionIdProblemRoute
  '/session/$sessionId/readiness': typeof SessionSessionIdReadinessRoute
  '/session/$sessionId/request': typeof SessionSessionIdRequestRoute
  '/session/$sessionId/summary': typeof SessionSessionIdSummaryRoute
  '/session/$sessionId/transition': typeof SessionSessionIdTransitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/session/new': typeof SessionNewRoute
  '/session/$sessionId/approach': typeof SessionSessionIdApproachRoute
  '/session/$sessionId/i-statement': typeof SessionSessionIdIStatementRoute
  '/session/$sessionId/problem': typeof SessionSessionIdProblemRoute
  '/session/$sessionId/readiness': typeof SessionSessionIdReadinessRoute
  '/session/$sessionId/request': typeof SessionSessionIdRequestRoute
  '/session/$sessionId/summary': typeof SessionSessionIdSummaryRoute
  '/session/$sessionId/transition': typeof SessionSessionIdTransitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/session/new': typeof SessionNewRoute
  '/session/$sessionId/approach': typeof SessionSessionIdApproachRoute
  '/session/$sessionId/i-statement': typeof SessionSessionIdIStatementRoute
  '/session/$sessionId/problem': typeof SessionSessionIdProblemRoute
  '/session/$sessionId/readiness': typeof SessionSessionIdReadinessRoute
  '/session/$sessionId/request': typeof SessionSessionIdRequestRoute
  '/session/$sessionId/summary': typeof SessionSessionIdSummaryRoute
  '/session/$sessionId/transition': typeof SessionSessionIdTransitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/history'
    | '/session/new'
    | '/session/$sessionId/approach'
    | '/session/$sessionId/i-statement'
    | '/session/$sessionId/problem'
    | '/session/$sessionId/readiness'
    | '/session/$sessionId/request'
    | '/session/$sessionId/summary'
    | '/session/$sessionId/transition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/session/new'
    | '/session/$sessionId/approach'
    | '/session/$sessionId/i-statement'
    | '/session/$sessionId/problem'
    | '/session/$sessionId/readiness'
    | '/session/$sessionId/request'
    | '/session/$sessionId/summary'
    | '/session/$sessionId/transition'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/history'
    | '/session/new'
    | '/session/$sessionId/approach'
    | '/session/$sessionId/i-statement'
    | '/session/$sessionId/problem'
    | '/session/$sessionId/readiness'
    | '/session/$sessionId/request'
    | '/session/$sessionId/summary'
    | '/session/$sessionId/transition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
  SessionNewRoute: typeof SessionNewRoute
  SessionSessionIdApproachRoute: typeof SessionSessionIdApproachRoute
  SessionSessionIdIStatementRoute: typeof SessionSessionIdIStatementRoute
  SessionSessionIdProblemRoute: typeof SessionSessionIdProblemRoute
  SessionSessionIdReadinessRoute: typeof SessionSessionIdReadinessRoute
  SessionSessionIdRequestRoute: typeof SessionSessionIdRequestRoute
  SessionSessionIdSummaryRoute: typeof SessionSessionIdSummaryRoute
  SessionSessionIdTransitionRoute: typeof SessionSessionIdTransitionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/new': {
      id: '/session/new'
      path: '/session/new'
      fullPath: '/session/new'
      preLoaderRoute: typeof SessionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/transition': {
      id: '/session/$sessionId/transition'
      path: '/session/$sessionId/transition'
      fullPath: '/session/$sessionId/transition'
      preLoaderRoute: typeof SessionSessionIdTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/summary': {
      id: '/session/$sessionId/summary'
      path: '/session/$sessionId/summary'
      fullPath: '/session/$sessionId/summary'
      preLoaderRoute: typeof SessionSessionIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/request': {
      id: '/session/$sessionId/request'
      path: '/session/$sessionId/request'
      fullPath: '/session/$sessionId/request'
      preLoaderRoute: typeof SessionSessionIdRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/readiness': {
      id: '/session/$sessionId/readiness'
      path: '/session/$sessionId/readiness'
      fullPath: '/session/$sessionId/readiness'
      preLoaderRoute: typeof SessionSessionIdReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/problem': {
      id: '/session/$sessionId/problem'
      path: '/session/$sessionId/problem'
      fullPath: '/session/$sessionId/problem'
      preLoaderRoute: typeof SessionSessionIdProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/i-statement': {
      id: '/session/$sessionId/i-statement'
      path: '/session/$sessionId/i-statement'
      fullPath: '/session/$sessionId/i-statement'
      preLoaderRoute: typeof SessionSessionIdIStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/approach': {
      id: '/session/$sessionId/approach'
      path: '/session/$sessionId/approach'
      fullPath: '/session/$sessionId/approach'
      preLoaderRoute: typeof SessionSessionIdApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  SessionNewRoute: SessionNewRoute,
  SessionSessionIdApproachRoute: SessionSessionIdApproachRoute,
  SessionSessionIdIStatementRoute: SessionSessionIdIStatementRoute,
  SessionSessionIdProblemRoute: SessionSessionIdProblemRoute,
  SessionSessionIdReadinessRoute: SessionSessionIdReadinessRoute,
  SessionSessionIdRequestRoute: SessionSessionIdRequestRoute,
  SessionSessionIdSummaryRoute: SessionSessionIdSummaryRoute,
  SessionSessionIdTransitionRoute: SessionSessionIdTransitionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
